apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: angular-webapp
  namespace: default
spec:
  interval: 1m0s
  url: https://rakeshj-bb.github.io/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ang
  namespace: default
spec: 
  chart:
     spec:
      chart: angular-node-chart
      sourceRef:
        kind: HelmRepository
        name: angular-webapp
      version: 2.0.0
  interval: 1m0s